// src/databauti/locations.ts

export const locationOptions: { [country: string]: string[] } = {
  Argentina: [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
    "La Plata",
    "Mar del Plata",
    "Bahía Blanca",
    "Resistencia",
    "San Miguel de Tucumán",
    "Salta",
    "San Salvador de Jujuy",
    "Ushuaia",
    "Paraná",
    "Concordia",
    "Posadas",
    "Neuquén",
    "San Carlos de Bariloche",
  ],
  Chile: [
    "Santiago",
    "Valparaíso",
    "Concepción",
    "Antofagasta",
    "Arica",
    "Iquique",
    "Puerto Montt",
    "Punta Arenas",
    "Rancagua",
    "Viña del Mar",
  ],
  Uruguay: [
    "Montevideo",
    "Punta del Este",
    "Salto",
    "Maldonado",
    "Paysandú",
    "Rivera",
    "Canelones",
    "Colonia",
    "Durazno",
    "Rocha",
  ],
  Brasil: [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Belo Horizonte",
    "Salvador",
    "Fortaleza",
    "Curitiba",
    "Porto Alegre",
    "Manaus",
    "Recife",
    "Belém",
    "Florianópolis",
    "Natal",
    "Campo Grande",
    "João Pessoa",
  ],
  Paraguay: [
    "Asunción",
    "Encarnación",
    "Ciudad del Este",
    "Concepción",
    "San Pedro",
    "Caacupé",
  ],
};

export const countries = Object.keys(locationOptions);
